version: '3'
services:
  metabase:
    image: tools/metabase:latest
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 5
        window: 120s
      placement:
        constraints: [node.role == manager]
    environment:
      - MB_DB_FILE=/var/lib/metabase/data/metabase.db
    ports:
      - 8082:3000
    volumes:
      - metabase_data:/var/lib/metabase/data
networks:
  default:
    external:
      name: services_networks
volumes:
  metabase_data:
    external: true